"""Content Enhancement Script - Batch 2
Expanding more thin documents + adding code examples and troubleshooting"""

from pymongo import MongoClient
from datetime import datetime, timezone

client = MongoClient('mongodb://localhost:27017')
db = client['test_database']
NOW = datetime.now(timezone.utc).isoformat()

def update_doc(title, new_content):
    result = db.documents.update_one(
        {'title': title},
        {'$set': {'content': new_content, 'updated_at': NOW}}
    )
    print(f"{'UPDATED' if result.modified_count else 'NOT FOUND'}: {title} ({len(new_content)} chars)")

# ============================================================
# 1. Assets & File Processing (1936 -> ~5000 chars)
# ============================================================
update_doc("Assets & File Processing", """# Assets & File Processing

How files are stored, served, and managed on the Emergent platform — from user uploads to generated images.

## The File Lifecycle

```mermaid
flowchart LR
    U[User Upload] --> V[Validation]
    V --> CH[Chunked Transfer]
    CH --> S[Storage Layer]
    S --> CDN[Serve via URL]
```

**Step-by-step:**

1. **User Upload** — File selected via frontend input or generated by a tool (e.g., `image_generation_tool`)
2. **Validation** — File type, size limits, and content checks applied
3. **Chunked Transfer** — Large files are split into chunks to bypass proxy limits (the Kubernetes ingress has a request body size limit)
4. **Storage** — Files stored on the pod's filesystem or uploaded to cloud storage
5. **Serve** — Available via URL for frontend display or download

## Storage Locations

| Location | What Goes Here | Persistence | Access |
|----------|---------------|-------------|--------|
| `/app/` | Application code, user files | Persists during pod lifetime | Direct filesystem |
| `/tmp/` | Temporary files, screenshots | Cleared on pod restart | Direct filesystem |
| Cloud Storage | Generated images, uploads | Permanent | URL-based |
| MongoDB GridFS | Document attachments | Permanent | API-based |

**Important:** Files stored on the pod filesystem (`/app/`, `/tmp/`) are **not permanent**. When the pod is recycled (after inactivity), these files are lost. Only MongoDB data and cloud-stored files survive pod restarts.

## Handling File Uploads in Your App

### Backend: Receiving Files

```python
from fastapi import UploadFile, File

@api_router.post("/upload")
async def upload_file(file: UploadFile = File(...)):
    # Validate file type
    allowed_types = ["image/png", "image/jpeg", "application/pdf"]
    if file.content_type not in allowed_types:
        raise HTTPException(400, "File type not allowed")
    
    # Validate file size (10MB limit)
    contents = await file.read()
    if len(contents) > 10 * 1024 * 1024:
        raise HTTPException(400, "File too large (max 10MB)")
    
    # Save to filesystem
    file_path = f"/app/uploads/{file.filename}"
    with open(file_path, "wb") as f:
        f.write(contents)
    
    return {"filename": file.filename, "size": len(contents)}
```

### Frontend: Uploading Files

```jsx
const handleUpload = async (event) => {
  const file = event.target.files[0];
  const formData = new FormData();
  formData.append("file", file);
  
  const response = await fetch(`${API}/upload`, {
    method: "POST",
    body: formData,
    // Note: Do NOT set Content-Type header — browser sets it 
    // automatically with the correct boundary for multipart
  });
  
  const data = await response.json();
  console.log("Uploaded:", data.filename);
};
```

### Chunked Upload for Large Files

For files larger than the proxy limit (~5MB), use chunked uploads:

```javascript
async function uploadChunked(file, chunkSize = 1024 * 1024) {
  const totalChunks = Math.ceil(file.size / chunkSize);
  const uploadId = crypto.randomUUID();
  
  for (let i = 0; i < totalChunks; i++) {
    const start = i * chunkSize;
    const chunk = file.slice(start, start + chunkSize);
    const formData = new FormData();
    formData.append("chunk", chunk);
    formData.append("uploadId", uploadId);
    formData.append("chunkIndex", i);
    formData.append("totalChunks", totalChunks);
    
    await fetch(`${API}/upload/chunk`, {
      method: "POST",
      body: formData,
    });
  }
  
  // Finalize: tell server to assemble chunks
  return fetch(`${API}/upload/finalize`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ uploadId, filename: file.name }),
  });
}
```

## Image Processing

### Generated Images (via AI)

When E1 generates images using `image_generation_tool` or `gpt-image-1`:

1. Image generated by the AI provider
2. Automatically uploaded to cloud storage
3. URL returned for use in your application
4. URLs are **permanent** — they don't expire with the pod

### Image Optimization Best Practices

| Technique | Implementation | Impact |
|-----------|---------------|--------|
| Compress on upload | Use `Pillow` to reduce quality to 80% | 50-70% size reduction |
| Serve correct size | Generate thumbnails for lists, full-size for detail views | Faster page loads |
| Use WebP format | Convert PNG/JPEG to WebP | 25-35% smaller than JPEG |
| Lazy loading | `<img loading="lazy" />` | Defer off-screen images |

## Troubleshooting File Issues

| Problem | Cause | Solution |
|---------|-------|----------|
| "File not found" after pod restart | Pod filesystem is ephemeral | Store files in MongoDB or cloud storage |
| Upload fails silently | Proxy body size limit exceeded | Use chunked uploads |
| Image URL returns 404 | Pod recycled, file was in `/tmp/` | Use cloud storage URLs instead |
| "Content-Type not set" | Missing `multipart/form-data` | Don't set Content-Type manually on FormData |
| Large upload timeout | File too large for single request | Implement chunked upload |
""")

# ============================================================
# 2. Rate Limiting Layers (2122 -> ~5000 chars)
# ============================================================
update_doc("Rate Limiting Layers", """# Rate Limiting Layers

Rate limiting on Emergent operates at multiple layers, each protecting different resources. Understanding these layers helps you debug "why is my request failing?" scenarios.

## The Rate Limiting Stack

```mermaid
flowchart TD
    REQ[Incoming Request] --> L1[Layer 1: Kubernetes Ingress<br/>Connection-level limits]
    L1 --> L2[Layer 2: Nginx<br/>Request rate limits]
    L2 --> L3[Layer 3: FastAPI Middleware<br/>Application-level limits]
    L3 --> L4[Layer 4: LLM Proxy<br/>Token budget limits]
    L4 --> APP[Application Logic]
```

## Layer Details

### Layer 1: Kubernetes Ingress

| Setting | Value | Purpose |
|---------|-------|---------|
| Max connections per IP | 100 | Prevent connection flooding |
| Request body size | ~5MB | Prevent memory exhaustion |
| Connection timeout | 60s | Free up stale connections |
| WebSocket timeout | 3600s | Allow long-lived connections |

**When you hit this:** You'll see a `413 Request Entity Too Large` or `503 Service Unavailable` error. This is the outermost layer — your request never reaches your application.

### Layer 2: Nginx Reverse Proxy

| Setting | Value | Purpose |
|---------|-------|---------|
| Requests per second | Varies | Prevent request flooding |
| Burst allowance | Yes | Short spikes are allowed |
| Proxy pass timeout | 120s | Prevent hung backends |

**When you hit this:** You'll see a `429 Too Many Requests` response from Nginx. The response won't have your application's error format — it'll be a plain Nginx error page.

### Layer 3: Application Middleware

This is where **you** control rate limiting in your FastAPI app:

```python
from fastapi import Request
from datetime import datetime, timezone
import time

# Simple in-memory rate limiter
rate_limit_store = {}

async def rate_limit_middleware(request: Request, call_next):
    client_ip = request.client.host
    now = time.time()
    
    # Clean old entries
    rate_limit_store[client_ip] = [
        t for t in rate_limit_store.get(client_ip, [])
        if now - t < 60  # 1-minute window
    ]
    
    # Check limit
    if len(rate_limit_store.get(client_ip, [])) >= 100:
        return JSONResponse(
            status_code=429,
            content={"detail": "Too many requests. Try again in a minute."}
        )
    
    # Record request
    rate_limit_store.setdefault(client_ip, []).append(now)
    return await call_next(request)
```

### Layer 4: LLM Proxy / Token Budget

The most nuanced layer — controls AI usage based on your balance:

| Check | What Happens | Error |
|-------|-------------|-------|
| Balance check before LLM call | If balance < estimated cost, call rejected | "Insufficient balance" |
| Token counting after call | Actual tokens deducted from balance | Balance updated |
| Rate limit per model | Provider-specific limits | "Rate limited by provider" |

## How to Identify Which Layer Blocked You

| Error Response | Layer | What to Do |
|---------------|-------|-----------|
| `413 Request Entity Too Large` | Kubernetes Ingress | Reduce payload size or use chunked uploads |
| `429` with Nginx HTML page | Nginx | Wait and retry, reduce request frequency |
| `429` with JSON `{"detail": "..."}` | Your Application | Check your rate limit settings |
| `402` or `{"error": "Insufficient balance"}` | LLM Proxy | Add balance in Profile → Universal Key |
| `503 Service Unavailable` | Any layer | Pod may be starting up — wait and retry |

## Implementing Rate Limiting in Your App

### Per-User Rate Limiting

```python
from collections import defaultdict
import asyncio

class RateLimiter:
    def __init__(self, max_requests=60, window_seconds=60):
        self.max_requests = max_requests
        self.window = window_seconds
        self.requests = defaultdict(list)
    
    def is_allowed(self, user_id: str) -> bool:
        now = time.time()
        # Remove expired entries
        self.requests[user_id] = [
            t for t in self.requests[user_id]
            if now - t < self.window
        ]
        if len(self.requests[user_id]) >= self.max_requests:
            return False
        self.requests[user_id].append(now)
        return True

limiter = RateLimiter(max_requests=30, window_seconds=60)
```

### Rate Limiting Best Practices

| Practice | Why |
|----------|-----|
| Use sliding windows, not fixed windows | Prevents burst at window boundaries |
| Return `Retry-After` header | Tells clients when to retry |
| Different limits for different endpoints | AI endpoints need stricter limits than static data |
| Log rate limit hits | Monitor for abuse patterns |
| Exempt health check endpoints | Monitoring shouldn't be rate-limited |

## Troubleshooting Rate Limits

| Symptom | Diagnosis | Fix |
|---------|-----------|-----|
| Random 429 errors | Nginx-level rate limiting | Check if you're making rapid sequential calls |
| 413 on file upload | Body size limit | Use chunked upload |
| AI features stop working | Token budget exhausted | Check balance in Profile → Universal Key |
| All requests failing | Pod starting up (503) | Wait 30 seconds, retry |
| Only POST requests failing | CSRF or rate limit on mutations | Check middleware configuration |
""")

# ============================================================
# 3. SSL/TLS & CORS (2180 -> ~5000 chars)
# ============================================================
update_doc("SSL/TLS & CORS", """# SSL/TLS & CORS

Security at the transport and browser level. Understanding these is essential for debugging "why can't my frontend talk to my backend?" problems.

## TLS on Emergent

```mermaid
flowchart LR
    B[Browser] -->|HTTPS| I[Ingress<br/>TLS Termination]
    I -->|HTTP| N[Nginx]
    N -->|HTTP| A[Your App<br/>Port 8001/3000]
```

**TLS terminates at the Kubernetes Ingress.** Your application code only sees plain HTTP traffic. This means:

| Layer | Protocol | Who Handles TLS? |
|-------|----------|-------------------|
| Browser ↔ Ingress | HTTPS (TLS 1.3) | Kubernetes cert-manager (automatic) |
| Ingress ↔ Nginx | HTTP | No TLS needed (internal) |
| Nginx ↔ App | HTTP | No TLS needed (internal) |

**You never need to configure SSL certificates in your app.** Emergent handles this automatically through Let's Encrypt certificates managed by cert-manager.

## CORS: Cross-Origin Resource Sharing

CORS is the browser's security mechanism that blocks frontend JavaScript from making requests to a different origin.

### What Is an "Origin"?

```
https://my-app.preview.emergentagent.com:443
  │          │                              │
  scheme     host                          port
```

Two URLs have the **same origin** only if scheme + host + port all match. Any difference = cross-origin.

### How CORS Works

```mermaid
sequenceDiagram
    participant B as Browser
    participant S as Server
    B->>S: OPTIONS /api/data (preflight)
    Note right of B: "Can I make a POST from this origin?"
    S->>B: 200 OK + CORS headers
    Note left of S: "Yes, these origins/methods are allowed"
    B->>S: POST /api/data (actual request)
    S->>B: 200 OK + data + CORS headers
```

**Preflight requests** happen automatically for "non-simple" requests (POST with JSON, custom headers, etc.). The browser sends an OPTIONS request first to check permissions.

### CORS Configuration on Emergent

```python
from starlette.middleware.cors import CORSMiddleware

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, list specific origins
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
```

**On Emergent, CORS is configured with `allow_origins=["*"]`** because the preview URL is dynamic and changes between sessions. In a production deployment, you'd restrict this to your specific domain.

### CORS Headers Explained

| Header | Purpose | Example |
|--------|---------|---------|
| `Access-Control-Allow-Origin` | Which origins can access | `*` or `https://example.com` |
| `Access-Control-Allow-Methods` | Which HTTP methods are allowed | `GET, POST, PUT, DELETE` |
| `Access-Control-Allow-Headers` | Which request headers are allowed | `Content-Type, Authorization` |
| `Access-Control-Allow-Credentials` | Allow cookies/auth headers | `true` or `false` |
| `Access-Control-Max-Age` | How long to cache preflight response | `3600` (1 hour) |

## Common Security Headers

Beyond CORS, production apps should include:

| Header | Purpose | Value |
|--------|---------|-------|
| `X-Content-Type-Options` | Prevent MIME sniffing | `nosniff` |
| `X-Frame-Options` | Prevent clickjacking | `DENY` or `SAMEORIGIN` |
| `Strict-Transport-Security` | Force HTTPS | `max-age=31536000; includeSubDomains` |
| `Content-Security-Policy` | Control resource loading | Complex; domain-specific |

## Troubleshooting CORS Issues

CORS errors are the #1 frustration for frontend developers. Here's how to debug them:

### The Error Message

```
Access to fetch at 'https://api.example.com/data' from origin 
'https://my-app.com' has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present.
```

### Decision Tree

| Check | If Yes | If No |
|-------|--------|-------|
| Is the backend running? | Continue | Start the backend first |
| Can you curl the endpoint? | CORS is the issue | Backend bug, not CORS |
| Does the response have CORS headers? | Headers are wrong | CORS middleware not applied |
| Is it a preflight (OPTIONS) request? | OPTIONS handler missing | Check allowed origins |
| Does the origin match allowed origins? | Check methods/headers | Add origin to allowed list |

### Common CORS Fixes

```python
# Fix 1: Ensure CORS middleware is added BEFORE routes
app = FastAPI()
app.add_middleware(CORSMiddleware, ...)  # Must be before router
app.include_router(api_router)           # After middleware

# Fix 2: Don't set CORS headers manually AND use middleware
# Pick one approach, not both — they conflict

# Fix 3: For cookies/auth, credentials must be true
# AND allow_origins cannot be "*" (use specific origins)
```

### Why CORS Only Affects Browsers

| Client | Subject to CORS? | Why |
|--------|-----------------|-----|
| Browser (fetch/XHR) | Yes | Browser enforces same-origin policy |
| curl | No | Command-line tools don't have origins |
| Postman | No | Not a browser, no same-origin policy |
| Server-to-server | No | CORS is a browser-only mechanism |
| Mobile app (native) | No | Native apps don't have origins |

This is why "it works in Postman but not in my app" is almost always a CORS issue.

## HTTPS Best Practices

| Practice | Why |
|----------|-----|
| Never mix HTTP and HTTPS | Mixed content is blocked by browsers |
| Use relative URLs for API calls | Automatically uses the page's protocol |
| Set `Secure` flag on cookies | Prevents cookies from being sent over HTTP |
| Use `REACT_APP_BACKEND_URL` | Ensures correct protocol in all environments |
""")

# ============================================================
# 4. Session Lifecycle (2323 -> ~5000 chars)
# ============================================================
update_doc("Session Lifecycle", """# Session Lifecycle

Understanding how sessions work on Emergent — from pod allocation to data persistence — is key to building reliable applications.

## The Complete Session Flow

```mermaid
sequenceDiagram
    participant U as User
    participant P as Platform
    participant K as Kubernetes
    participant Pod as Pod
    participant DB as MongoDB

    U->>P: Start a job
    P->>K: Request pod allocation
    K->>Pod: Create pod with resources
    Pod->>Pod: Start services (backend, frontend, MongoDB)
    Pod->>DB: Initialize database
    Pod->>P: Ready signal
    P->>U: Session active, preview URL assigned
    
    Note over U,Pod: Development Session Active
    
    U->>Pod: Send messages, write code
    Pod->>DB: Store data
    Pod->>Pod: Auto-commit to Git
    
    Note over U,Pod: Inactivity Period
    
    K->>Pod: Scale down (recycle pod)
    Note over Pod: Pod filesystem lost
    Note over DB: MongoDB data preserved
```

## Pod Lifecycle Stages

| Stage | What Happens | Duration |
|-------|-------------|----------|
| **Allocation** | Kubernetes finds resources, creates pod | 10-30 seconds |
| **Initialization** | Services start (supervisor, MongoDB, backend, frontend) | 15-45 seconds |
| **Active** | Full development environment running | Until inactivity timeout |
| **Idle** | No user activity detected | Configurable timeout |
| **Recycled** | Pod terminated, resources freed | Immediate |
| **Wake-up** | New pod allocated on next request | 10-30 seconds |

## What Survives Pod Recycling?

| Data Type | Survives? | Why |
|-----------|-----------|-----|
| MongoDB documents | Yes | Database is persisted |
| Git commits | Yes | Committed to remote |
| Uploaded files (cloud) | Yes | Stored externally |
| Environment variables | Yes | Restored from config |
| Files in `/app/` | Partial | Only committed files |
| Files in `/tmp/` | No | Temporary filesystem |
| Running processes | No | Pod is completely new |
| In-memory state | No | New process, new memory |
| WebSocket connections | No | Must reconnect |

## Session State Management

### Server-Side Sessions

```python
# Store session data in MongoDB (survives pod recycling)
@api_router.post("/session/create")
async def create_session():
    session_id = str(uuid.uuid4())
    session = {
        "id": session_id,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "data": {}
    }
    await db.sessions.insert_one(session)
    return {"session_id": session_id}

@api_router.get("/session/{session_id}")
async def get_session(session_id: str):
    session = await db.sessions.find_one(
        {"id": session_id}, {"_id": 0}
    )
    if not session:
        raise HTTPException(404, "Session not found")
    return session
```

### Client-Side State (localStorage)

```javascript
// Persists across page refreshes, survives pod recycling
// because it's stored in the USER'S browser

// Save state
localStorage.setItem("user-prefs", JSON.stringify({
  theme: "dark",
  sidebarWidth: 280,
  lastViewedDoc: "abc-123"
}));

// Restore state
const prefs = JSON.parse(
  localStorage.getItem("user-prefs") || "{}"
);
```

### Choosing the Right Storage

| Need | Use | Why |
|------|-----|-----|
| User preferences (theme, layout) | `localStorage` | Browser-local, instant, no API call |
| Application data (documents, records) | MongoDB | Persistent, queryable, shared |
| Temporary computation results | In-memory (variables) | Fast, but lost on refresh |
| Large files | Cloud storage | Survives pod recycling |
| Authentication tokens | HTTP-only cookies | Secure, automatic on requests |

## Handling Pod Cold Starts

When a user returns after pod recycling, the experience should be smooth:

```jsx
// Frontend: Detect cold start and show loading
function Dashboard() {
  const [loading, setLoading] = useState(true);
  const [connectionError, setConnectionError] = useState(false);

  const loadData = async () => {
    try {
      const response = await fetch(`${API}/documents`);
      if (response.ok) {
        const data = await response.json();
        setDocuments(data);
        setLoading(false);
      }
    } catch (error) {
      // Backend still starting up
      setConnectionError(true);
      setTimeout(loadData, 3000); // Retry in 3 seconds
    }
  };

  useEffect(() => { loadData(); }, []);

  if (loading || connectionError) {
    return <LoadingScreen message={
      connectionError 
        ? "Server is waking up..." 
        : "Loading..."
    } />;
  }
  // ... render dashboard
}
```

## Troubleshooting Session Issues

| Symptom | Cause | Solution |
|---------|-------|----------|
| Data disappeared after break | Pod recycled, data was in filesystem | Store important data in MongoDB |
| "Connection refused" on return | Pod is cold-starting | Wait 30s, implement retry logic |
| WebSocket won't connect | Old pod gone, new pod allocated | Implement auto-reconnect |
| Environment variables missing | `.env` file not committed | Ensure `.env` is in Git |
| Different preview URL | New pod = new URL | Use `REACT_APP_BACKEND_URL` from .env |
| Login state lost | Session cookie expired or pod changed | Store auth state in MongoDB |
""")

print("\n=== Enhancement Batch 2 Complete ===")
print("Updated: Assets & File Processing, Rate Limiting, SSL/TLS & CORS, Session Lifecycle")
